### PR TITLE
Switch to github fork of prettify

### PR DESCRIPTION
**Pull request by jean**
The google code one is returning 404 on
https://google-code-prettify.googlecode.com/svn/loader/prettify.css

### CODE REVIEW

**Comment by jean** [comment]
This is the pull request ;-)

**Comment by peterhellberg** [comment]
Sorry, I was looking through my issues list and didn’t notice that it was a PR ;)

**Comment by jean** [comment]
Hehe :-)
Just a note, here's some background on rawgit: https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions
It's not from github; it's possible to use just `rawgit.com` for dev (non-CDN); it may be a good idea to link to a version tag in case prettify gets any updates.

**Comment by peterhellberg** [comment]
I’ve been thinking of skipping the dependency on prettify if it becomes an issue (Since we don’t strictly _need_ to have highlighting of responses)

**Pull request merged**
